language: java
jdk: oraclejdk8
after_success: ./.travis.after_success.sh

# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

# Build snapshots for master
# A master build is also needed for the cache to work
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/addon

env:
  global:
  - secure: QyXNA3eg0EowPuSHYHaOgErA3s0NjbLuQK9lYkWLzb91AsoUQGUsVvuQJUv0oDlQ9hw8njhPbpDZh9za4mljLsm33rKChv5dnjOJPu/2Rd6Ke5LZilSjILr96tMK8jwUCaYIT4Zm8qtSTPxlSpQjYvHYBP9BUEG27Fl/Zq3z7fQDSyUy8A6GE8eXBlgpuG+Sog7QhhkvkH0wu+/XYBPLCuikB39lVMelvnOSUHOMnxyspgJ7ZFJ99HoVNFFuNH4CEOAGIHgm0T/FYYUXVo7dD10g/E+QQnv42GTPtbNWP3D12vkDBalrpwsLkQpTPRGKF9zxGVSw2N7u19MEY7/IzOmh2TfYp8JiWXdm5TtXrogBnilOvwKageMc0eD6ws/tAxR5waYV+u9ffTngR8Og8XaVGPaeQTopJYDSVvR2uYYGTQ2SXuoywM8ddX/ZIIYQzKQ6CABgvuH4+UuLaQUMK6xS5BrHSLAtrnnVeKQUVUtSNJv9Xs33c4NSapHedsoh4+uaZYAJRnj7MbA436I2xYcQ8P8YsMfGaxq8VDQEQpgMo+6YupY4oUs/vVOki9xoJeqeYWWwhpjqXlH0BO9WDHr1oEqVbKg9GEuqwt1sPIwbmeO5kZdmQuN8YV3af6Vr+2ixuCO0trsl9KDsCmtd5pWFBQs+obBzZjYt0uwvojU=
  - secure: vmLe22c0PXZvwPL1BFoG8CvzyoIpRQikM7PQOETWrA9SqIfjPK6At0TNslHF1gEwQJvubTTqrat3Bfr7qIbFtPV1UTxR8DWe3tPUoX3o3ccAlXpEY4Ps3Ui2UrKhxhptRpLw+OYxDQNeiyPeGd09fa0BGzfiC7sozOCRvUT+vKxvX0zxrrY6VMHhwFga68kHJByHj+zin8J55B6ubbsgq+bPNi52XoWTzl/4Yr/a6FMwiYFuS1/t3h6MdRoki5LCIqxdWcfmrGdCTMdHOjs1zmCcQrduG4bwiYk79ePrSaT4CMtZpBqfVbi5IlWp2hBq+vrPz/DUjv/CK55sY5yx2wJyi7WUxKKWCR75c8BltacotUhKJ8OcfWOd099KsBDvKED3MJw41cIbZgsyWsSGimjNKu52w7IdaAOS+8pZbi7mnH3P41EFKN5SXb5Bet+BXx6pB5OoOD51tlbzaikN7bLnaalTllWJ771tOjg1xHjSt/nZlBoiLZiYPv0bzQuIvK22QCoLy2OYpY3gc/DfaNwT1bSPi8de6OOwL++s1KB8mXX0i8p1vOJ2+NCsk7pvAwNaYniN7mVIz0gltZH9bPDe9K12LGG1U10VD7fMqk5uTa95fZuRHa7H9xiVAI+q2ycPkeuul4GmcQsVGTqwI2mIrBhApSKZbOWqOOK6hg0=
  - secure: bDPhZvAfMMsHFi4WoZx+ToOmH4DiGRJ123QSWceXe80L6dDpW/vg8djf/8O1h3QpeKXPh2Ovh6PyYk2RL5XBdr17cMi0YLKtkzgQhbm5xak+JB6qRbqtY95N+fqOITR/161kvqsT+1ng9H1ZXcCLZjUIZJ7+BBnx7BRgMb8192Qg8yEm3ZpFQATZuU3d0AcKgt220Ve98Uaaow9bjcEsBu3JEEb9cZXdacw6hTDLTE3oX2T3WJVqLT1XprGZutPSDdWXaaLMXFmw3+27aWRUdU+Fqts20UPWCfkoyEqIjFQA8HgicHWf+TWA17Mq4cmYXNoPcfcVMc3VbXvnWOy3PjgWcJRGV3SqJbexA73paOXgWzruiFlPcB/jJ+E9KyNt67n/G0iufx/2qUSKGwMSRYHye5pYW8TQMXBVUi2PKqDGtuwDcsdPSaFdyb4v8SNSLCcRRXmJxOV7UwZvER95D54M0+1CE4dJFfRCPSnqaaSbcSRqZasDAz2n4zEGgCCZ7COC4AfbBuBRBWrLgYYJpv9NQJoWoeZ2B+u+7vuYf4CGnpzVdUAq6qDA0JuU9ZusFpDfXv4LHOOt0d8XAmv6ZhzGJ8jGW8GXuNdZD+JSY1vHmjten5yPmyV6ne6uRMiABkWyVVZdw34l6ns7Ek9gxZ8Na1ZRKTLW2lc7cyT2K4w=
