language: java
jdk: oraclejdk8
after_success: ./.travis.after_success.sh

# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

# Build snapshots for master
# A master build is also needed for the cache to work
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/addon

env:
  global:
  - secure: Z3FwMYsAMYoMbcKfvwVoqt3BR7BD6GmF2eGYKMKcXAOBwe9K22nRZ2mXgg8U9EbE1AJ6CeJ6SYyfCkUOI4mozQgG1Vf9t6pOW/zguDJim36XdY+jdrmn252upwVQFrXA32XJ8e3uU6N5hTe4OokngCwap/uzamhzKvpnLvg/yUqViX2f8Y+1szPTsv7OvYxFzmQrfLa1Md65Ox9kBG9bAfWkePmze5YEZ7R6vgqpH0jhfIfwAZvP+JBc0F3hLWFzjosK3cjXaUENtEIAVBds7lFU2KGeCz6uF7H92Wy8z+x01C4eXyhavjwv2wxaWi5P1q1AHR/BWhDVk7b2VAI9wix/jaGVYW5KvuM00k2WG9yEsKEVflG2ky93nTTPaB3lkWmNp7wF3vW4OKhs0UddjfiFTD0f71JQBvwWoqZ39h1CrApV0OrSd4/c/WVCNBAoSV/4xk+QLHp/u1cZDpvVmV6zyOLlD73F+hc3Zyi4HwsAGTPUjQXWBj8Jp883HflDdzfomMELRsKdGYGnImubBNaTHa+d9IVDbST7UgaNRJowEZpnlwq0CPks+JpvH+MFFJJCEJJ9LKkKnm1jMRzNBYh7HdIkaaFbi063ixiMCghpMM1FRG8Pboh+s2iz+ut/g5vaIyb7+vW15/URWOEN9ky1DqQtokVby098hMUeu1g=
  - secure: om+WzlBqeMh3hIgCmGfu7sBCQm0e3c9McoAN0r9i6f1mfIhlSWmrvDwcI2RHWcpOYK2hI7SE7SbZmuy2ctiZ1VMmo5cSTkM5b3VQ2/GUsMgPsWbA6knNSantnQaAvPzEi+d/1J+5jYjF1EqZldtVUE0r1K5rEp9ScPzQLGLScYB9WSUrXxVQYCLEx8g0Zh+u3fD8BdbSZUo78Cv1AaqIGdHQcrHht8YoLHfBa9F3F7IJEWYS9wEaMiYaH6qa51zVa+mzkwgfCr7FeEYlTha1E+m5vEUBOiBWWOmyWwNpPimDt6in/ptcBe0dJ66zlYr9ebNMlmNu65NeHMoVJtqaodGZhggmVexQMpkSC3RlbM4TnAHkQuFSVPPVTX/Detlq0hLVIIPI6Q1az6i19NSg0ydSiePiqB/EEB3AqSINeBmCDeSh22xifX0PhXz42n3atKN7ia+WRBlysXpRBgcav8D3xvVuRCXoJ7xcAHnbXIOjLVfnXLRoyCfaC9ADYCSB8dIzBca9SdyNlWN5nKKU5j94dSAlxjVlpuZ5SCNYwvcmz8+6DKzOe3zMlfl1/JSLmVlXK2lOR1T9DlvbyRaWUrX1X+/3ju9QzwjTIKTbUtWNP4R8b7hq8asjx53wOzbieUkIV5QQ0ExZMLjsfHOE8P3b4tCKhk8c88mcMXqv7/w=
